name: nf-core-m6APipe-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - R=3.4.1
  - python=2.7
  - fastqc=0.11.8
  - bedtools=2.27.1
  - ucsc-gtftogenepred=357 
  - hisat2=2.1.0
  - bowtie2=2.2.5
  - bwa=0.7.17
  - star=2.6.1b
  - tophat=2.1.1
  - samtools=0.1.19
  - rseqc=2.6.4
  - bioconductor-edger=3.22.5
  - bioconductor-deseq2=1.20.0
  - htseq=0.11.2
  - cufflinks=2.2.1
  - bioconductor-exomepeak=2.14.0
  - macs2=2.1.2 (r=3.4.1)
  - r-dplyr=0.7.6
  - r-readr=1.1.1
  - perl=5.26.2
  - python=2.7.13
  - meme=5.0.2
  - homer=4.9.1
  - QNB=1.1.11
  - MetPeak=1.0.0
  - MetDIff=1.0.0
  - mspc=3.3
  - numpy=1.16.0
  - MATK=1.0.0
  - bioconductor-genogam=1.8.0
  - pepr=1.1.24
  - deeptools=3.1.3
  - picard=2.18.27